{% set name = "gengetopt" %}
{% set version = "2.23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/gnu/gengetopt/gengetopt-{{ version }}.tar.xz
  sha256: b941aec9011864978dd7fdeb052b1943535824169d2aa2b0e7eae9ab807584ac

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - autoconf
    - automake
    - libtool
    - texinfo

test:
  commands:
    - gengetopt --version

about:
  home: https://www.gnu.org/software/gengetopt/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: "This program generates a C function that uses getopt_long function to parse the command line options, to validate them and fills a struct."
  doc_url: https://www.gnu.org/software/gengetopt/gengetopt.html
  dev_url: http://savannah.gnu.org/bugs/?group=gengetopt

extra:
  recipe-maintainers:
    - j-4
    - wolfv
