travis:
  secure:
    BINSTAR_TOKEN: HhmspdGZ8g32yYC6GkLsl7FM/yRLp+bNQlvNZX2OmtBSzuKHAReC2mF+Pfm0iDYmcV65CcVN/GhF/UuSvlhYaZE2hhBCxAksAdUuXAahumYqBtd3syTQg7vsAdplWzuekX9pAOhVPhiTyvNelQG92O3gtk/hj1JQZa2Y0UO+oFbh677ljfZg6LWKE2AjrO8Kia1RJFn79Zbbcs5RR8QF+x8AT2TRXtB2oHGmR75QS8aSOOQKHUc2NaFwFNfOUdP1BMQsPMxeqMdPSQDq4N2CKQMMzicbHm7ArajPEc44QEW5vKawb9CRr2H9AcALJJ4/rnVcEEAAsKfjmATFn9ZIfH4yMdCEOn8VBsHtp43P7THx/8FDwzPX0IgB1UWc5dM1JrfiwnZne4oaIsn6cLohHZe9TK6fqtF/KB2ohsJ8BAcSjii+g1ESD2xazlt3lN9p9wJIECod0AqcU6ItipwYVKI6HSVquw64JfJW5JirHR+nTlSNYQpV7CNsu+GQEnR9szt3CQN0fF2HeULwh9O6wBo3r0ADLfdaKj06Xhgx+wMX3LRJjZNCLRbNsMkSwlpTUeiZ04KCM7TEX/S6kCahTt89LggYf1rwGBQL/onYegH7Pqj3BQo9HKwr5qzqaQhn6Bju2c3TCs1zo4EQCawgLgo4f4upY13AAqqNlJbKYvI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
