appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zbhZxC6hBBFOd2yvmEev+hyjpktokdHZNk8wKWbc+9q1/OcT/cgyGoW0/7xWOPen9SNrnxTHfOl0KrYneBa0dZrsapJv3EKvPXlUgfhmz2OnG93vyavRP1MBdmuM4iG1iVLtP5J/SHOvGeIMDtV6MBLpBFDPZkRuQhuv5AMQajo8lS7+FvVfDapHKqdS6r1byC2WUDvHfpVkQ0E3iOT7kKnrzTYoBQCKJ7VWe4bOxHSGhARqWA+pbWDPJAl09QrDiElbe9TPfudKWNALBP3YvUqnjkAe5/YOzwKe3BDFvMZBDQfrFWdtDbbVKq8lzqRjL4bcAFXdigJOLTMMKnnTujbgTJ3oHCfpYc5c0Ybd+AN6sg3XioCW40uwp/12XUp1IgGFG5KeW7c8qRB4znyJDcxCtpBT8wloJN5JeMdAzlabrUdZpqlN9xKq57ARakpC3ze29EUgYOqYf/WtaGKp1k0EWdpzHJg8O489PsAyqKXsGhWfvOnrT4lx3mXEgum1vz8pV/pMhHUugW3P7wLHiBtjj2yRo5ACVkwWvBn7puTFErTkaBrBbjSmhF0rWHyy+/ifmTiZN1pOZzj9JKPFwiO/KRbF4pZyJvaWpiP0OnA3vtqbeRUZZizZ4RPRUMzto8BwFeDWQdB2UtUI5pirj6EhDjKW5ne+eXVTVcc2lB4=}
